#!/bin/bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

cleanup() {
  rm -rf "$SCRIPT_DIR/venv"
}

if [[ ! -d "$SCRIPT_DIR/venv" ]]
then
  python3 -m venv "$SCRIPT_DIR/venv"
  ret=$?
  if [ $ret -ne 0 ]
  then
    echo "Error when creating virtual environment. Are python3 and python3-venv installed?"
    cleanup
    exit 1
  fi
  "$SCRIPT_DIR"/venv/bin/pip3 install -r "$SCRIPT_DIR"/requirements.txt
  ret=$?
  if [ $ret -ne 0 ]
  then
    echo "Error installing dependencies."
    cleanup
    exit 2
  fi
  if [[ ! -f "/usr/lib/python3/dist-packages/uno.py" ]]
  then
    echo "Cannot find libreoffice conversion libraries. Is libreoffice installed?"
    cleanup
    exit 3
  else
    ln -sf /usr/lib/python3/dist-packages/uno.py venv/lib/python3.10/site-packages/uno.py
    ln -sf /usr/lib/python3/dist-packages/unohelper.py venv/lib/python3.10/site-packages/unohelper.py
  fi
fi

. venv/bin/activate
python3 "$SCRIPT_DIR"/src/docx_to_pdf.py "$@"
deactivate
