#!/bin/bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

cleanup() {
  rm -rf "$SCRIPT_DIR/venv"
}

"$SCRIPT_DIR"/scripts/create_venv "$SCRIPT_DIR"
if [ $? -ne 0 ]
then
  cleanup
fi

. "$SCRIPT_DIR"/venv/bin/activate
python3 "$SCRIPT_DIR"/src/server.py "$@"
deactivate
