#!/bin/bash

ROOT_DIR=$1

if [[ ! -d "$ROOT_DIR/venv" ]]
then
  python3 -m venv "$ROOT_DIR/venv"
  ret=$?
  if [ $ret -ne 0 ]
  then
    echo "Error when creating virtual environment. Are python3 and python3-venv installed?"
    cleanup
    exit 1
  fi
  "$ROOT_DIR"/venv/bin/pip3 install -r "$ROOT_DIR"/requirements.txt
  ret=$?
  if [ $ret -ne 0 ]
  then
    echo "Error installing dependencies."
    cleanup
    exit 2
  fi
  if [[ ! -f "/usr/lib/python3/dist-packages/uno.py" ]]
  then
    echo "Cannot find libreoffice conversion libraries. Is libreoffice installed?"
    cleanup
    exit 3
  else
    python_major=$(python3 --version | sed "s/Python //" | sed "s/.[0-9]*$//")
    ln -sf /usr/lib/python3/dist-packages/uno.py "$ROOT_DIR"/venv/lib/python"$python_major"/site-packages/uno.py
    ln -sf /usr/lib/python3/dist-packages/unohelper.py "$ROOT_DIR"/venv/lib/python"$python_major"/site-packages/unohelper.py
  fi
fi